---
title: "progress-report-Amanda-Ohmer"
author: "Amanda Ohmer"
date: "2024-4-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rvest)
```

```{r}
url <- "https://en.wikipedia.org/wiki/2023_Baseball_Hall_of_Fame_balloting"
html <- read_html(url)
html
```

```{r}
tables <- html %>% html_table(fill=TRUE)
tables %>% str()
```

```{r}
bbwaa <- tables[[3]]  # candidates on the BBWAA Ballot
vet1 <- tables[[5]] # Early Baseball Era Committee
vet2 <- tables[[6]] # Golden Days Era Committee
bbwaa %>% head()
```











```{r}
website <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
code <- read_html(website)
code
```

```{r}
table <- code %>% html_table(fill=TRUE)
table %>% str()
```

```{r}
baseball <- table [[1]]
```

```{r}
baseball
```

```{r}
colnames(baseball)[1] <- "Rank"
colnames(baseball)[2] <- "Name"
colnames(baseball)[3] <- "Year on Ballot"
colnames(baseball)[4] <- "Votes"
colnames(baseball)[5] <- "%Votes"
colnames(baseball)[6] <- "HOFm"
colnames(baseball)[7] <- "HOFs"
colnames(baseball)[8] <- "Yrs"
colnames(baseball)[9] <- "WAR"
colnames(baseball)[10] <- "WAR7"
colnames(baseball)[11] <- "JAWS"
colnames(baseball)[12] <- "Jpos"
colnames(baseball)[13] <- "Batting G"
colnames(baseball)[14] <- "Batting AB"
colnames(baseball)[15] <- "Batting R"
colnames(baseball)[16] <- "Batting H"
colnames(baseball)[17] <- "Batting HR"
colnames(baseball)[18] <- "Batting RBI"
colnames(baseball)[19] <- "Batting SB"
colnames(baseball)[20] <- "Batting BB"
colnames(baseball)[21] <- "Batting BA"
colnames(baseball)[22] <- "Batting OBP"
colnames(baseball)[23] <- "Batting SLG"
colnames(baseball)[24] <- "Batting OPS"
colnames(baseball)[25] <- "Batting OPS+"
colnames(baseball)[26] <- "Pitching W"
colnames(baseball)[27] <- "Pitching L"
colnames(baseball)[28] <- "Pitching ERA"
colnames(baseball)[29] <- "Pitching ERA+"
colnames(baseball)[30] <- "Pitching WHIP"
colnames(baseball)[31] <- "Pitching G"
colnames(baseball)[32] <- "Pitching GS"
colnames(baseball)[33] <- "Pitching SV"
colnames(baseball)[34] <- "Pitching IP"
colnames(baseball)[35] <- "Pitching H"
colnames(baseball)[36] <- "Pitching HR"
colnames(baseball)[37] <- "Pitchin BB"
colnames(baseball)[38] <- "Pitching SO"
colnames(baseball)[39] <- "Pos Summary"


```

```{r}
baseball
```


```{r}
baseball <- baseball[baseball$Rank != 'Rk',]
```

```{r}
baseball
```

